### ISSUE TITLE
Changing saved audio filename

### ISSUE THREAD

**Issue by gcunhase** [techiaith/pyfestival#3]
Hello,

I'm having an issue with changing the location of the saved audio file. Would there be an easy way to do so?

Cheers

**Comment by pjrobertson** [comment]
Helo Gwena

Post the code you are using so we can understand the problem you are having

Diolch

**Comment by gcunhase** [comment]
Hi Diolch,

Thank you for your reply.

I'm trying to overload the *_textToWav* function in the *_festival.cpp* file so I can also send as parameter the location I'd like to save my audio file:

```cpp
static PyObject* _textToWav(PyObject* self, PyObject* args, PyObject* argsFilename) {
    [...]
    const char* saved_filename;
    if (!PyArg_ParseTuple(argsFilename, "s:_textToWav", &saved_filename)) return NULL;

    EST_String tmpfile = saved_filename;
    [...]
    return filename;
}
```

After that, I should be able to theoretically modify *textToWavFile* in *festival.py* as follows:
```python
def textToWavFile(text, filename=None):
    [...]
    if filename:
        file = _festival._textToWav(text, filename)
    else:
        file = _festival._textToWav(text)
    return file
```

However, I still get the following error in the line where I try to send *filename* as argument:
```
TypeError: _textToWav() takes exactly 1 argument (2 given)
```

Best,
Gwena

**Comment by pjrobertson** [comment]
Seems like you're trying to change the cpp code. In that case you need to recompile the festival.so library after changing the file. I suggest you look into how to use `PyArg_ParseTuple()` correctly in order to parse multiple args. (Try looking at https://docs.python.org/2/c-api/arg.html).

It seems what you want is something like (Note: this is untested):


```
static PyObject* _textToWav(PyObject* self, PyObject* args) {
    [...]
    const char* saved_filename;
    if (!PyArg_ParseTuple(args, "s|s:_textToWav", &text, &saved_filename)) return NULL;

    EST_String tmpfile = saved_filename;
    [...]
    return filename;
}
```

Since this is more of a coding support query, and not a bug in pyfestival itself (this is related to modifying an internal/private function) I will close this issue now. I suggest you ask for further support in somewhere like Stack Overflow

P.S 'Diolch' is the word for 'Thank you' in Welsh, my name is Patrick! ;-)

**Comment by gcunhase** [comment]
Thank you very much for your suggestions and sorry for posting this query here, Stack Overflow would have been more appropriate, so I'll make sure to do that next time :)

P.S: this is so funny hahaha diolch for teaching me a little bit of welsh Patrick :D
